/*si hacemos:*/
SELECT * FROM Products ORDER BY ProductName ASC
/*NOS APARECEN PRIMERO LOS NULL*/
/*PERO SI HACEMOS:*/
SELECT * FROM Products
WHERE ProductName IS NOT NULL
ORDER BY ProductName ASC/*NO APARECEN LOS NULLS*/
/*SI USAMOS IS NULL SOLO BUSCA LOS NULLS*/
SELECT * FROM Products
WHERE ProductName IS NULL
ORDER BY ProductName ASC/*NOS APARECEN SOLO LOS NULLS*/

/*RECORDAR SI USAMOS UN NOT Y UN NULL ES LO MIMSOQ UE USAR NOT NULL*/